---
- name: configuration check
  hosts: all
  tasks:
    - name: configuration check
      fail: msg="Make sure project_name and secret_key are correctly defined"
      when: project_name|default('') == '' or secret_key|default('') == ''


# Development Machines
- name: configure and deploy the development environment
  sudo: yes
  hosts: vagrant
  gather_facts: no
  roles:
    - dbserver
    - gunicorn
    - nginx
