- name: install essential packages
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
    - build-essential
    - git-core
    - python-dev
    - python-setuptools
    - python-software-properties
    - libpq-dev
    - libxslt1-dev
    - unzip
    - ssl-cert

- name: ensure pip latest version
  command: easy_install pip

- include: install_supervisor.yml
