---
#
# Installation of requirements.txt in virtualenv
#

- name: system-wide install of virtualenv and virtualenvwrapper
  pip: name={{ item }} state=present
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: Modify bashrc for virtualenvwrapper (1/2)
  lineinfile: dest={{ home }}/.bashrc
              regexp="^export WORKON_HOME"
              line="export WORKON_HOME=$HOME/.virtualenvs"
              state=present

- name: Modify bashrc for virtualenvwrapper (2/2)
  lineinfile: dest={{ home }}/.bashrc
              regexp="^source /usr/local/bin/virtualenvwrapper.sh"
              line="source /usr/local/bin/virtualenvwrapper.sh"
              state=present

- name: Modify bashrc to activate virtualenv on login
  lineinfile: dest={{ home }}/.bashrc
              regexp="^workon "
              line="workon {{ project_name }}"
              state=present
  when: development

- name: Modify bashrc to go to manage directory on login
  lineinfile: dest={{ home }}/.bashrc
              regexp="^cd"
              line="cd {{ django_manage_path }}"
              state=present
  when: development
